### ISSUE TITLE
[C] Code won't compile on Win7 64-bit

### ISSUE THREAD

**Issue by bisherbas** [formulahendry/vscode-code-runner#259]
**VS Code 1.20.1
Code Runner 0.8.7**

Highlighted the code below and selected Run Code in the right click menu.

```
#include <stdio.h>
int main()
{
   // printf() displays the string inside quotation
   printf("Hello, World!");
   return 0;
}
```
Error

```
[Running] cd "w:\SourceCode\myProj\" && gcc -m32 tempCodeRunnerFile.c -o tempCodeRunnerFile && "w:\SourceCode\myProj\"tempCodeRunnerFile
This version of C:\\cygwin\\bin\gcc.exe is not compatible with the version of Windows you're running. Check your computer's system information to see whether you need a x86 (32-bit) or x64 (64-bit) version of the program, and then contact the software publisher.

[Done] exited with code=1 in 0.077 seconds
```

However, I can manually compile the code using `gcc` in the `bash` terminal.

**Comment by bisherbas** [comment]
Running on the `CMD` terminal displayes the exact same error.

`"code-runner.runInTerminal": true` did not make any difference.

**Comment by formulahendry** [comment]
So it is the issue of the `C:\\cygwin\\bin\gcc.exe`, no related to this extension. Closing as external.
You may either make `C:\\cygwin\\bin\gcc.exe` work or set the default terminal in VS Code as `bash` instead of `CMD` (refer to https://code.visualstudio.com/docs/editor/integrated-terminal#_windows)
