### ISSUE TITLE
Please add debug support

### ISSUE THREAD

**Issue by f-lima** [formulahendry/vscode-code-runner#45]
I just tried add it at pull requests instead issues but no text field open to me can write it.

But, if possible, add support to debug programs.
I would like to have it at least for Groovy, Swift, Java, Ruby and C#.
VB.Net support would be nice too.

Thanks.

**Comment by formulahendry** [comment]
Hi @f-lima , thanks for your feedback! However, since debug support is very different from each language, it would not be appropriate to put the debug support into the same extension. Therefore, debug support may be out of scope for this extension. 😄 You may try to find other specific extensions for debug support per language.
