### ISSUE TITLE
A few ideas

### ISSUE THREAD

**Issue by HopedWall** [formulahendry/vscode-code-runner#47]
Hi, would it be possible to add a 'run code' option under the File menu? Also I think it would be nice if you choose to open a new window and see the results there.
Thank you!

**Comment by formulahendry** [comment]
Hi @HopedWall ,
For 'run code' option under the File menu, the VS Code does not expose API for extension to make that. Currently, we are not able to implement this.
For choice to open a new window, do you want a setting to config, so that every time code is running, a new window will be opened and the output is clear to show? In that case, you may try below setting to clear previous output before each run. Otherwise, too many window will be opened after many runs. Let me know if you have other purpose for new window.
```json
{
    "code-runner.clearPreviousOutput": true
}
```
