### ISSUE TITLE
Can we work with transpiled sources?

### ISSUE THREAD

**Issue by dewdad** [formulahendry/vscode-code-runner#9]
Lets say I'm looking at a es6 script and I have the Babel watch task open to transpile my code to a "build" directory in the root of my project. How would I use this extension in such a scenario?

**Comment by formulahendry** [comment]
I am afraid this extension does not support this scenario, since it is targeting to be a lightweight code runner.
But I think you could try the [babel-node](https://babeljs.io/docs/usage/cli/#babel-node), seems like it could compile and run ES6 in one command.
You may overwrite the `javascript` section of `code-runner.executorMap` as below:
```json
{
    "code-runner.executorMap": {
        "javascript": "babel-node"
    }
}
```
Hope that would work.

**Comment by formulahendry** [comment]
Hi @dewdad , with the recent release of Code Runner, we have supported customized parameters. You could refer to below settings to build your owns with babel
```json
{
    "code-runner.executorMap": {
        "java": "cd $dir && javac $fileName && java $fileNameWithoutExt",
        "c": "gcc $fullFileName && ./a.out"
    }
}
```
